version: '3'

services:
  app:
    image: janhkrueger/matplotlib_devcontainer:20230911
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  default:
    name: matplotlib-dev-network